# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ballon fortælling
email: ludvigsoerensen@gmail.com
description: > # Her kan du lære om ballonens historie, igennem en billede -og historiefyldt hjemmeside
url: "http://lutski.github.io/ballon-fort-lling-KomIt/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
